apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdfdiff-ingress
  namespace: pdfdiff
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  tls:
    - secretName: pdfdiff-prod-tls
      hosts:
        - api.example.com
        - admin.example.com
        - viewer.example.com
        - flower.example.com
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000
    - host: admin.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 80
    - host: viewer.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: viewer
                port:
                  number: 80
    - host: flower.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flower
                port:
                  number: 5555
