apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdfdiff-local-ingress
  namespace: pdfdiff
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - secretName: pdfdiff-local-tls
      hosts:
        - api.pdfdiff-turbo.local
        - admin.pdfdiff-turbo.local
        - viewer.pdfdiff-turbo.local
        - flower.pdfdiff-turbo.local
  rules:
    - host: api.pdfdiff-turbo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000
    - host: admin.pdfdiff-turbo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 80
    - host: viewer.pdfdiff-turbo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: viewer
                port:
                  number: 80
    - host: flower.pdfdiff-turbo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flower
                port:
                  number: 5555
