apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: pdfdiff
spec:
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: pdfdiff
spec:
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: viewer
  namespace: pdfdiff
spec:
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: flower
  namespace: pdfdiff
spec:
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: pdfdiff
spec:
  type: NodePort
