apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pdfdiff
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - persistent-volumes.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - tika.yaml
  - api.yaml
  - beat.yaml
  - worker.yaml
  - flower.yaml
  - admin.yaml
  - viewer.yaml
