apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  namespace: pdfdiff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
        - name: tika
          image: apache/tika:2.9.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9998
---
apiVersion: v1
kind: Service
metadata:
  name: tika
  namespace: pdfdiff
spec:
  selector:
    app: tika
  ports:
    - name: http
      port: 9998
      targetPort: 9998
