apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: pdfdiff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: localhost/pdfdiff-turbo-worker:1.1.19
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: pdfdiff-config
            - secretRef:
                name: pdfdiff-secret
          command:
            - celery
            - -A
            - app.core.celery_app.celery_app
            - worker
            - --loglevel=INFO
            - --concurrency=2
            - --prefetch-multiplier=1
            - -Q
            - jobs,pages
          volumeMounts:
            - name: pdfdiff-data
              mountPath: /data
      volumes:
        - name: pdfdiff-data
          persistentVolumeClaim:
            claimName: pdfdiff-data
